build/mvn checks local downloaded binary ahead before network access

diff --git a/build/mvn b/build/mvn
--- a/build/mvn
+++ b/build/mvn
@@ -45,59 +45,58 @@ install_app() {
   curl_opts="--progress-bar ${curl_opts}"
   wget_opts="--progress=bar:force ${wget_opts}"
 
-  if [ -z "$3" -o ! -f "$binary" ]; then
-    # check if we already have the tarball
-    # check if we have curl installed
-    # download application
-    [ ! -f "${local_tarball}" ] && [ $(command -v curl) ] && \
-      echo "exec: curl ${curl_opts} ${remote_tarball}" 1>&2 && \
-      curl ${curl_opts} "${remote_tarball}" > "${local_tarball}"
-    # if the file still doesn't exist, lets try `wget` and cross our fingers
-    [ ! -f "${local_tarball}" ] && [ $(command -v wget) ] && \
-      echo "exec: wget ${wget_opts} ${remote_tarball}" 1>&2 && \
-      wget ${wget_opts} -O "${local_tarball}" "${remote_tarball}"
-    # if both were unsuccessful, exit
-    [ ! -f "${local_tarball}" ] && \
-      echo -n "ERROR: Cannot download $2 with cURL or wget; " && \
-      echo "please install manually and try again." && \
-      exit 2
-    cd "${_DIR}" && tar -xzf "$2"
-    rm -rf "$local_tarball"
-  fi
+  # check if we already have the tarball
+  # check if we have curl installed
+  # download application
+  [ ! -f "${local_tarball}" ] && [ $(command -v curl) ] && \
+    echo "exec: curl ${curl_opts} ${remote_tarball}" 1>&2 && \
+    curl ${curl_opts} "${remote_tarball}" > "${local_tarball}"
+  # if the file still doesn't exist, lets try `wget` and cross our fingers
+  [ ! -f "${local_tarball}" ] && [ $(command -v wget) ] && \
+    echo "exec: wget ${wget_opts} ${remote_tarball}" 1>&2 && \
+    wget ${wget_opts} -O "${local_tarball}" "${remote_tarball}"
+  # if both were unsuccessful, exit
+  [ ! -f "${local_tarball}" ] && \
+    echo -n "ERROR: Cannot download $2 with cURL or wget; " && \
+    echo "please install manually and try again." && \
+    exit 2
+  cd "${_DIR}" && tar -xzf "$2"
+  rm -rf "$local_tarball"
 }
 
 # Determine the Maven version from the root pom.xml file and
 # install maven under the build/ folder if needed.
 install_mvn() {
   local MVN_VERSION=`grep "<maven.version>" "${_DIR}/../pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
-  MVN_BIN="$(command -v mvn)"
-  if [ "$MVN_BIN" ]; then
-    local MVN_DETECTED_VERSION="$(mvn --version | head -n1 | awk '{print $3}')"
-  fi
-  # See simple version normalization: http://stackoverflow.com/questions/16989598/bash-comparing-version-numbers
-  function version { echo "$@" | awk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }'; }
-  if [ $(version $MVN_DETECTED_VERSION) -ne $(version $MVN_VERSION) ]; then
-    local APACHE_MIRROR=${APACHE_MIRROR:-'https://www.apache.org/dyn/closer.lua'}
-    local MIRROR_URL_QUERY="?action=download"
-    local MVN_TARBALL="apache-maven-${MVN_VERSION}-bin.tar.gz"
-    local FILE_PATH="maven/maven-3/${MVN_VERSION}/binaries"
-
-    if [ $(command -v curl) ]; then
-      if ! curl -L --output /dev/null --silent --head --fail "${APACHE_MIRROR}/${FILE_PATH}/${MVN_TARBALL}${MIRROR_URL_QUERY}" ; then
-        # Fall back to archive.apache.org for older Maven
-        echo "Falling back to archive.apache.org to download Maven"
-        APACHE_MIRROR="https://archive.apache.org/dist"
-        MIRROR_URL_QUERY=""
-      fi
+  MVN_BIN="${_DIR}/apache-maven-${MVN_VERSION}/bin/mvn"
+  if [ ! -f "$MVN_BIN" ]; then
+    MVN_BIN="$(command -v mvn)"
+    if [ "$MVN_BIN" ]; then
+      local MVN_DETECTED_VERSION="$(mvn --version | head -n1 | awk '{print $3}')"
     fi
+    if [ $MVN_DETECTED_VERSION != $MVN_VERSION ]; then
+      local APACHE_MIRROR=${APACHE_MIRROR:-'https://www.apache.org/dyn/closer.lua'}
+      local MIRROR_URL_QUERY="?action=download"
+      local MVN_TARBALL="apache-maven-${MVN_VERSION}-bin.tar.gz"
+      local FILE_PATH="maven/maven-3/${MVN_VERSION}/binaries"
 
-    install_app \
-      "${APACHE_MIRROR}/${FILE_PATH}" \
-      "${MVN_TARBALL}" \
-      "apache-maven-${MVN_VERSION}/bin/mvn" \
-      "${MIRROR_URL_QUERY}"
+      if [ $(command -v curl) ]; then
+        if ! curl -L --output /dev/null --silent --head --fail "${APACHE_MIRROR}/${FILE_PATH}/${MVN_TARBALL}${MIRROR_URL_QUERY}" ; then
+          # Fall back to archive.apache.org for older Maven
+          echo "Falling back to archive.apache.org to download Maven"
+          APACHE_MIRROR="https://archive.apache.org/dist"
+          MIRROR_URL_QUERY=""
+        fi
+      fi
 
-    MVN_BIN="${_DIR}/apache-maven-${MVN_VERSION}/bin/mvn"
+      install_app \
+        "${APACHE_MIRROR}/${FILE_PATH}" \
+        "${MVN_TARBALL}" \
+        "apache-maven-${MVN_VERSION}/bin/mvn" \
+        "${MIRROR_URL_QUERY}"
+
+      MVN_BIN="${_DIR}/apache-maven-${MVN_VERSION}/bin/mvn"
+    fi
   fi
 }
 
