Migrate build/mvn to download tgz from the ASF site to Maven Central

diff --git a/build/mvn b/build/mvn
--- a/build/mvn
+++ b/build/mvn
@@ -28,37 +28,74 @@ if [ "$CI" ]; then
   export MAVEN_CLI_OPTS="--no-transfer-progress --errors --fail-fast"
 fi
 
-# Installs any application tarball given a URL, the expected tarball name
-## Arg1 - URL
-## Arg2 - Tarball Name
-## Arg3 - URL query string
+# Installs any application tarball given a URL, the expected tarball name,
+# and, optionally, a checkable binary path to determine if the binary has
+# already been installed. Arguments:
+# 1 - Mirror host
+# 2 - URL path on host
+# 3 - URL query string
+# 4 - checksum suffix
+# 5 - Tarball Name
+# 6 - Checkable Binary
 install_app() {
-  local remote_tarball="$1/$2$3"
-  local local_tarball="${_DIR}/$2"
+  local mirror_host="$1"
+  local url_path="$2"
+  local url_query="$3"
+  local checksum_suffix="$4"
+  local local_tarball="${_DIR}/$5"
+  local binary="${_DIR}/$6"
+  local remote_tarball="${mirror_host}/${url_path}${url_query}"
+  local local_checksum="${local_tarball}.${checksum_suffix}"
+  local remote_checksum="${mirror_host}/${url_path}.${checksum_suffix}${url_query}"
 
-  # setup `curl` and `wget` silent options if we're running on Jenkins
-  local curl_opts="-L"
-  local wget_opts=""
-  curl_opts="--progress-bar ${curl_opts}"
-  wget_opts="--progress=bar:force ${wget_opts}"
+  local curl_opts="--retry 3 --silent --show-error -L"
+  local wget_opts="--no-verbose"
 
-  # check if we already have the tarball
-  # check if we have curl installed
-  # download application
-  [ ! -f "${local_tarball}" ] && [ $(command -v curl) ] && \
-    echo "exec: curl ${curl_opts} ${remote_tarball}" 1>&2 && \
-    curl ${curl_opts} "${remote_tarball}" > "${local_tarball}"
-  # if the file still doesn't exist, lets try `wget` and cross our fingers
-  [ ! -f "${local_tarball}" ] && [ $(command -v wget) ] && \
-    echo "exec: wget ${wget_opts} ${remote_tarball}" 1>&2 && \
-    wget ${wget_opts} -O "${local_tarball}" "${remote_tarball}"
-  # if both were unsuccessful, exit
-  [ ! -f "${local_tarball}" ] && \
-    echo -n "ERROR: Cannot download $2 with cURL or wget; " && \
-    echo "please install manually and try again." && \
-    exit 2
-  cd "${_DIR}" && tar -xzf "$2"
-  rm -rf "$local_tarball"
+  if [ ! -f "$binary" ]; then
+    # check if we already have the tarball
+    # check if we have curl installed
+    # download application
+    if [ ! -f "${local_tarball}" -a "$(command -v curl)" ]; then
+      echo "exec: curl ${curl_opts} ${remote_tarball}" 1>&2
+      curl ${curl_opts} "${remote_tarball}" > "${local_tarball}"
+      if [ ! -z "${checksum_suffix}" ]; then
+        echo "exec: curl ${curl_opts} ${remote_checksum}" 1>&2
+        curl ${curl_opts} "${remote_checksum}" > "${local_checksum}"
+      fi
+    fi
+    # if the file still doesn't exist, lets try `wget` and cross our fingers
+    if [ ! -f "${local_tarball}" -a "$(command -v wget)" ]; then
+      echo "exec: wget ${wget_opts} ${remote_tarball}" 1>&2
+      wget ${wget_opts} -O "${local_tarball}" "${remote_tarball}"
+      if [ ! -z "${checksum_suffix}" ]; then
+        echo "exec: wget ${wget_opts} ${remote_checksum}" 1>&2
+        wget ${wget_opts} -O "${local_checksum}" "${remote_checksum}"
+      fi
+    fi
+    # if both were unsuccessful, exit
+    if [ ! -f "${local_tarball}" ]; then
+      echo -n "ERROR: Cannot download ${remote_tarball} with cURL or wget; please install manually and try again."
+      exit 2
+    fi
+    # Checksum may not have been specified; don't check if doesn't exist
+    if [ "$(command -v shasum)" ]; then
+      if [ -f "${local_checksum}" ]; then
+        echo "  ${local_tarball}" >> ${local_checksum} # two spaces + file are important!
+        # Assuming SHA512 here for now
+        echo "Verifying checksum from ${local_checksum}" 1>&2
+        if ! shasum -a 512 -c "${local_checksum}" > /dev/null ; then
+          echo "Bad checksum from ${remote_checksum}"
+          exit 2
+        fi
+      fi
+    else
+      echo "Skipping checksum because shasum is not installed." 1>&2
+    fi
+
+    cd "${_DIR}" && tar -xzf "${local_tarball}"
+    rm -rf "${local_tarball}"
+    rm -f "${local_checksum}"
+  fi
 }
 
 # See simple version normalization: http://stackoverflow.com/questions/16989598/bash-comparing-version-numbers
@@ -77,24 +114,28 @@ install_mvn() {
     local MVN_DETECTED_VERSION="$(mvn --version | head -n1 | awk '{print $3}')"
   fi
   if [ $(version $MVN_DETECTED_VERSION) -ne $(version $MVN_VERSION) ]; then
-    local APACHE_MIRROR=${APACHE_MIRROR:-'https://www.apache.org/dyn/closer.lua'}
-    local MIRROR_URL_QUERY="?action=download"
     local MVN_TARBALL="apache-maven-${MVN_VERSION}-bin.tar.gz"
-    local FILE_PATH="maven/maven-3/${MVN_VERSION}/binaries"
+    local FILE_PATH="org/apache/maven/apache-maven/${MVN_VERSION}/${MVN_TARBALL}"
+    local MIRROR_BASE=${MAVEN_MIRROR:-https://maven-central.storage-download.googleapis.com/maven2/}
+    local MIRROR_URL_QUERY=""
 
     if [ $(command -v curl) ]; then
-      if ! curl -L --output /dev/null --silent --head --fail "${APACHE_MIRROR}/${FILE_PATH}/${MVN_TARBALL}${MIRROR_URL_QUERY}" ; then
+      if ! curl -L --output /dev/null --silent --head --fail "${MIRROR_BASE%/}/${FILE_PATH}${MIRROR_URL_QUERY}" ; then
         # Fall back to archive.apache.org for older Maven
         echo "Falling back to archive.apache.org to download Maven"
-        APACHE_MIRROR="https://archive.apache.org/dist"
+        FILE_PATH="maven/maven-3/${MVN_VERSION}/binaries/${MVN_TARBALL}"
+        MIRROR_BASE="https://archive.apache.org/dist"
         MIRROR_URL_QUERY=""
       fi
     fi
 
     install_app \
-      "${APACHE_MIRROR}/${FILE_PATH}" \
+      "${MIRROR_BASE%/}" \
+      "${FILE_PATH}" \
+      "${MIRROR_URL_QUERY}" \
+      "sha512" \
       "${MVN_TARBALL}" \
-      "${MIRROR_URL_QUERY}"
+      "apache-maven-${MVN_VERSION}/bin/mvn"
 
     MVN_BIN="${_DIR}/apache-maven-${MVN_VERSION}/bin/mvn"
   fi
